### ISSUE TITLE
ReactView - SubscribedChannelView

### ISSUE THREAD

**Issue by chasestarr** [newtonian-platypus/greenCast#33]

**Comment by chasestarr** [comment]
Blocking out subscribed channel view in files: `/app/components/subscribedChannelView.jsx`, `/app/components/subscribedChannelItemView.jsx`.

**Todo:**

From an array of channelIds
- [x] User will see a channel card for each subscription
  - [x] Send a request to grab channel data for each channel id
  - [x] Populate card with title, image, description
  - [x] Add data-attribute to each card with the channel id
- [x] User can click on a card to display all channel episodes in the feed view
- [x] User can unsubscribe from a channel within the card, ex. button

**Comment by chasestarr** [comment]
Two new functions passed down to each `subscribedChannelItemView`

``` javascript

unsubscribe(channelId) {
  console.log(channelId);
}

showEpisodes(feedUrl) {
  console.log(feedUrl);
}
```

Currently only logs the channel id and feedUrl. Will eventually trigger a feedView or userView re-render.

**Comment by chasestarr** [comment]
PR: https://github.com/newtonian-platypus/greenCast/pull/34
